<?php
/** @var $this \Zend\View\Renderer\PhpRenderer */
/** @var $element \Zend\Form\ElementInterface */
$suffix = $element->getOption('suffix');
?>
<?php if ($element instanceof \Zend\Form\Element\Submit): ?>
    <div class="form-row submit">
        <?= $this->formElement($element) ?>
    </div>
<?php else: ?>
    <div class="form-row<?php if ($element->getAttribute('combine-next')): ?> combine-next<?php endif ?>">
        <?php if ($element->getLabel()): ?>
            <?= $this->formLabel($element) ?>
        <?php endif ?>
        <div class="inputs">
            <?= $this->formElement($element) ?>
            <?php if ($suffix): ?>
                <?= $suffix ?>
            <?php endif ?>
        </div>
        <?php
        $messages = $element->getMessages();
        ?>
        <?php if (!empty($messages)): ?>
            <?= $this->formElementErrors($element, array('class' => 'errors')) ?>
        <?php endif ?>
    </div>
<?php endif ?>