<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Zend\Form\ElementInterface     $element
 * @var string                          $label
 * @var array                           $labelAttributes
 * @var string                          $labelPosition
 * @var bool                            $renderErrors
 */
?>
<div class="form-row radio">
    <?php if ($label): ?>
        <div class="label"><?= $label ?></div>
    <?php endif ?>
    <div class="inputs">
        <?= $this->formRadio($element) ?>
    </div>
    <?php if ($renderErrors): ?>
        <?= $this->formElementErrors($element, array('class' => 'error')) ?>
    <?php endif ?>
</div>
