<?php
/** @var $this \Zend\View\Renderer\PhpRenderer */
/** @var $pages array[] */

/**
 * @param array $page
 * @return string
 */
function getAnchorName($page)
{
    if ($page['name']) {
        return $page['name'];
    }
    return preg_replace('/[^a-zA-Z]/', '-', strtolower($page['label']));
}

$this->headLink()->appendStylesheet($this->basePath('admin/css/tabs.css'));
$this->headScript()->appendFile($this->basePath('admin/js/tabs.js'));
?>
<div class="tabbed">
    <ul class="tabs">
        <?php foreach ($pages as $i => $page): ?>
            <li<?php if ($i === 0): ?> class="active"<?php endif ?>>
                <a href="#<?= getAnchorName($page) ?>"><?= $page['label'] ?></a>
            </li>
        <?php endforeach ?>
    </ul>
    <?php foreach ($pages as $i => $page): ?>
        <article<?php if ($i === 0): ?> class="active"<?php endif ?>>
            <a name="<?= getAnchorName($page) ?>"></a>
            <?= $this->partial($page['template'], $page['values']) ?>
        </article>
    <?php endforeach ?>
</div>